RainLoop/rainloop-webmail

rainloop/v/0.0.0/langs/nl.ini

Translation for BUTTON_REQUEST_DSN

Updated Dutch translation (#467)

---

rainloop/v/0.0.0/langs/de.ini

Just translated new strings to german (DE).

Translated new strings

---

rainloop/v/0.0.0/langs/it.ini

Updated italian translation

---

plugins/ldap-change-password/index.php

The list of fields taken from https://github.com/RainLoop/rainloop-webmail/blob/master/plugins/ldap-change-password/ChangePasswordLdapDriver.php#L116-L117

Describe all options for ldap-change-password

---

rainloop/v/0.0.0/app/localization/webmail/en_GB.yml

Not wishing to be pedantic, but I have just tweaked this language file to use "configure" instead of "configurate".
Cheers

Minor typo in webmail -> settings -> security

---

dev/Model/Message.jsx
dev/View/User/MailBox/MessageView.js
rainloop/v/0.0.0/app/libraries/MailSo/Mail/MailClient.php
rainloop/v/0.0.0/app/libraries/MailSo/Mail/Message.php
rainloop/v/0.0.0/app/libraries/MailSo/Mime/Enumerations/Header.php
rainloop/v/0.0.0/app/libraries/RainLoop/Actions.php
rainloop/v/0.0.0/app/localization/webmail/_source.en.yml
rainloop/v/0.0.0/app/localization/webmail/fr_FR.yml
rainloop/v/0.0.0/app/templates/Views/User/MailMessageView.html

Hello,
This patch adds an unsubscribe button if the message contains a List-Unsubscribe header.

Add unsubscribe button

---

plugins/postfixadmin-change-password/ChangePasswordPostfixAdminDriver.php

Without it, u can change password, but u can't login after password change.

Add missing {PLAIN-MD5} before md5 hash

---

plugins/postfixadmin-change-password/ChangePasswordPostfixAdminDriver.php

Add other missing {type} before hash

---

CODE_OF_CONDUCT.md

Code of conduct proposal  to avoid unfortunate experience faced for a potential contributor in #1408 in future
Taken from http://contributor-covenant.org/
Issue related discussion here https://github.com/RainLoop/rainloop-webmail/issues/1412
:heart:

Code of conduct proposal

---

rainloop/v/0.0.0/app/libraries/MailSo/Sieve/ManageSieveClient.php

Fixed managesieve plain login

---

plugins/hmailserver-change-password/index.php
plugins/ispconfig-change-password/index.php
plugins/ispmail-change-password/index.php
plugins/ldap-change-password/index.php
plugins/ldap-contacts-suggestions/index.php
plugins/mailcow-change-password/index.php
plugins/postfixadmin-change-password/index.php
rainloop/v/0.0.0/app/libraries/PHP-OAuth2/Client.php

This PR resolves the issue presented in #1474

Misspellings in error messages

---

plugins/auto-domain-grab/index.php

This simply works as it should

Hotfix plugins/auto-domain-grab/index.php

---

build/owncloud/rainloop-app/lib/RainLoopHelper.php

use default data directory if not defined in NextCloud config

---

dev/Styles/MessageView.less

Hello There,
Thank you for this great piece of software. I added a feature to restrict images size on the message view. It's good for pictures sent at full size.
Have a nice day.

Content image max width size set to 100%

---

rainloop/v/0.0.0/app/libraries/RainLoop/Actions.php

Remove X-Mailer header if hide_x_mailer_header = Off

Fix hide_x_mailer_header config option behaviour

---

rainloop/v/0.0.0/app/localization/webmail/fi_FI.yml

```fi_FI.SETTINGS_LABELS.LABEL_THEMES_NAME ``` suppose to be "Teemat",  not emat.

fi_FI LABEL_THEMES_NAME propose

---

build/owncloud/rainloop-app/admin.php
build/owncloud/rainloop-app/ajax/admin.php
build/owncloud/rainloop-app/ajax/personal.php
build/owncloud/rainloop-app/app.php
build/owncloud/rainloop-app/appinfo/app.php
build/owncloud/rainloop-app/appinfo/info.xml
build/owncloud/rainloop-app/lib/RainLoopHelper.php
build/owncloud/rainloop-app/personal.php

This is a small patch to get app working on latest Owncloud 10.3.2.
I didn't found major issues after those changes.

Comply with Owncloud 10.3.2

---

rainloop/v/0.0.0/app/libraries/MailSo/Base/Crypt.php

This change allows the use of https://pecl.php.net/package/xxtea

Add support for PECL xxtea

---

rainloop/v/0.0.0/app/libraries/MailSo/Sieve/ManageSieveClient.php
rainloop/v/0.0.0/app/libraries/RainLoop/ServiceActions.php

Make some changes in order to make work Google document viewer, and ManageSieve integration (tested only with PHP 7.3).
This fixes are related to issue #2076 and #2074 (partially)

Google Document viewer and Managesieve Fixes

---

rainloop/v/0.0.0/app/libraries/MailSo/Imap/ImapClient.php

There's a bug in the MailSo parser which will crash root folders that have square brackets.
See #2037
This patch solves it.

Resolve issue #2037
