RainLoop/rainloop-webmail

rainloop/v/0.0.0/app/libraries/MailSo/Base/Utils.php

When pulling apart the username and domain for domain checking and such, break on the last @ symbol instead of the first one.  Dovecot master usernames can look like `username@domain.com*adminuser@domain.com`.

Break username and domain from login on last @ instead of first @

---

rainloop/v/0.0.0/app/libraries/MailSo/Mail/MailClient.php

It appears to have originally been backwards which broke date range searches.

Fix logic on date range search

---

rainloop/v/0.0.0/app/libraries/RainLoop/Actions.php

Since PHP 5.6, `ZipArchive::open` will return `ZipArchive::ER_NOENT` if the `ZipArchive::CREATE` option is not given and the file doesn't exist, while previously, it was created without error with only `ZipArchive::OVERWRITE`.

Add `ZipArchive::CREATE` flag for PHP 5.6

---

rainloop/v/0.0.0/langs/fr.ini

In French cryptography terminology, "Décrypter" means breaking encryption to get the plaintext (when not knowing the encryption key), while "Déchiffrer" means recovering a plaintext with the encryption key.
Link: https://fr.wikipedia.org/wiki/Cryptographie
Link: http://www.bortzmeyer.org/cryptage-n-existe-pas.html

Use proper terminology

---

dev/View/Popup/Compose.js

The findIdentityByMessage searches the message "to", "cc", "bcc" and "delivered-to" headers looking for an email address that matches one of the user's identities.  If a match is found, then that identity is used in preference to the default identity.
Unfortunately, findIdentityByMessage gives too great a weight to the default identity.  The existing algorithm works well on a system such as gmail, which uses "+" addressing for alternate email addresses.  For example, imagine you have a gmail account "me@gmail.com" with an alternate identity "me+alternate@gmail.com".  In this instance, if you send an email to "me+alternate@gmail.com", you will receive the following headers:
To: me+alternate@gmail.com
Delivered-To: me+alternate@gmail.com
This works great with the existing algorithm; the …

Fixes #693: findIdentityByMessage always selects the default identity

---

.gitignore
plugins/postfixadmin-change-password/ChangePasswordPostfixAdminDriver.php
plugins/postfixadmin-change-password/index.php

**Modified the postfixadmin-change-password plugin to give users these additional options for MySQL:**
* Specify the table name
* Specify the column name for user names
* Specify the column name for the passwords

Modified the postfixadmin-change-password plugin

---

plugins/postfixadmin-change-password/ChangePasswordPostfixAdminDriver.php
plugins/postfixadmin-change-password/index.php

I try it just now, compatible with Postfixadmin and Dovecot password schemes.
http://wiki.dovecot.org/Authentication/PasswordSchemes
linked to : https://github.com/RainLoop/rainloop-webmail/issues/939

Add support for SHA256-CRYPT and SHA512-CRYPT crypt schemes #939

---

npm-shrinkwrap.json
package.json

This helps prevent breaking builds when something is unexpectedly updated upstream.
This set of versions work, as far as `gulp` is concerned.
BTW, `CONTRIBUTING.md` links to http://www.rainloop.net/contribute/, which says "Work in progress.". I guess let's remove that step for now?

Shrinkwrap to control dependency versions

---

rainloop/v/0.0.0/app/libraries/MailSo/Base/Utils.php

In my setup, initial version of RemoveHeaderFromHeaders does not remove properly multi-line Headers (only the first line is removed). As a consequence, when using php mail() option for outgoing e-mail, strange things happen when the "To" field contains more than 3 recipients.

Fix incorrect handling of multi-line Header

---

dev/Styles/Compose.less

Two changes:
- Caused header overflow to scroll
- Minimized width of labels
Below are before/after screenshots from an iPhone 5 size screen. Notice how scrolling the header of the composition window does not affect the text editor part.
_...and after scrolling to the right..._

Improve composition on small screens

---

rainloop/v/0.0.0/app/templates/Views/User/PopupsCompose.html

By wrapping the two "from" line buttons on the composition popup in a `<span class="pull-right">` tag, they will now break lines together instead of separately. See below:

Improve button wrapping behavior

---

package.json

Both ```progress.js``` and ```knockout-projections``` tags / version numbers are prefixed with a ```v```. ```npm install``` fails on Alpine Linux 3.4 with npm version 3.10.3

Fix npm version numbers for Github packages

---

gulpfile.js

gulp-chmod expects values in octal, while the previous values were in decimal.
This resulted in incorrect permissions on build output files, which caused
the next build step to fail.

Fix permissions of built files.

---

makedeb.sh
rainloop/v/0.0.0/include.php

This script will generate a Debian-style package from the latest build of Rainloop. It's a fairly simple package, so it should be compatible with all Debian-based distributions. Rainloop itself is extracted to `/usr/share/rainloop`, and the data files are stored in `/var/lib/rainloop`. Permissions are set automatically. After installing this package, setting up a websever (or symlinking from a web-accessible directory) to `/usr/share/rainloop` is all that's necessary to begin using the software.
NB: This sort of script isn't the [recommended way to create a Debian package](https://www.debian.org/doc/manuals/maint-guide/start.en.html), so more work would be required to include it in the Debian repositories. Aside from the packaging details, the now-superfluous `rainloop/v/$VERSION` …

Create Debian Package

---

rainloop/v/0.0.0/app/libraries/RainLoop/Actions.php

When you receive an e-mail from an address with uppercase characters, Rainloop is not able to pull the correct image. This fixes it (tested).
Please see this site for more background information: http://gravatar.com/site/implement/hash/

Fix Gravatar when e-mail address contains uppercase characters

---

rainloop/v/0.0.0/app/libraries/RainLoop/Actions.php

Hello!
First of all, I want to congratulate you for the excellent tool that Rainloop is!
We are using version 1.11.3, and we are getting great results. However, we noticed that Rainloop did not support the standard "Spam" and "Trash" folders of the mail server we used (MailEnable 8.56). To solve the problem, simply add the lines in the file "app / libraries / RainLoop / Actions.php".
Thank you!

Added MailEnable 'Junk E-mail' and 'Deleted Items' folders support.

---

rainloop/v/0.0.0/app/libraries/MailSo/Mime/Enumerations/Header.php

As per [RFC 2045](https://tools.ietf.org/html/rfc2045#section-3), the correct way is "MIME-Version". At least one
email filter (Rspamd) is known to [penalize](https://github.com/vstakhov/rspamd/blob/5f037021c35e0394bc5bd12ee7b0c9aaa7f37fe3/rules/headers_checks.lua#L539-L546) the wrong case.

Fix the case for 'Mime-Version'

---

rainloop/v/0.0.0/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php

RainLoop does a lot of SQL queries like `SELECT id_prop, id_contact, prop_type, prop_value FROM rainloop_ab_properties WHERE prop_type IN (30,15,16,18) AND id_contact IN (173812,757514);` which takes a lot of time if the `rainloop_ab_properties` is big (quite noticeable with  ~6 million rows).
Use this to create index on an existing table:
`CREATE INDEX id_contact_prop_type_rainloop_ab_properties_index ON rainloop_ab_properties(id_contact, prop_type);`

Create index for id_contact and prop_type on rainloop_ab_properties

---

rainloop/v/0.0.0/app/libraries/RainLoop/Actions.php

In #1284, we noticed a conflict of headers "already sent" when an image is lazy loaded in the body of a message displayed in Rainloop. This little fix seems to fix it without visible regressions.
However, this should be reviewed carefully by people more knowledgeable on that part of the Rainloop code.
Thanks!

Fixing #1284, conflict in headers creation when loading images in body message, "Cannot modify header information - headers already sent"

---

plugins/change-password-custom-sql/ChangePasswordCustomSqlDriver.php
plugins/change-password-custom-sql/index.php

This is a fix for this issue:
https://github.com/RainLoop/rainloop-webmail/issues/1790
It fixes the SQL injection vulnerability that I found in this plugin.
I rewrote the database code to make use of PDO prepared statement and bound variables instead of `str_replace()`.
I also improved the description in the plugin config.
I tried to respect backwards compatibility with the current version of the plugin, so that current users of the plugin won't need to re-write their custom queries. 
However it could conceivable fail for a few edge cases. For example, PDO prepared statements can't have dynamic column names such as ``SELECT :domain ...``. But who would want this?

Custom SQL password plugin - SQL injection vulnerability fix

---

plugins/postfixadmin-change-password/ChangePasswordPostfixAdminDriver.php

The [PHP `str_shuffle()`](http://php.net/manual/en/function.str-shuffle.php) documentation states:
```
This function does not generate cryptographically secure values, and should not be used for cryptographic purposes.
```
This change makes use of [`random_bytes()`](http://php.net/manual/en/function.random-bytes.php) if it's available and falls back to the old (probably ok) `str_shuffle()` implementation.

Use `random_bytes` if available in postfix plugin

---

plugins/auto-domain-grab/index.php

auto-domain-grab will get MX record for Host. If MX is not found, it'll use mail.domain.com like before.
close #1318

auto-domain-grab use MX record for Host

---

plugins/ldap-contacts-suggestions/LdapContactsSuggestions.php
plugins/ldap-contacts-suggestions/index.php

When sending an e-mail, typing in the field **To:** makes the code query only 2 fields in an LDAP directory (related to the recipient's name and e-mail address). This change aims to add to that query also the **uid**, or some other useful unique identifier, while still retrieving only the name and e-mail address. This is useful for people working in environments where they know themselves only by user/login names (which might be completely different from their real names and/or e-mail addresses).

Added support to additional search field (defaults to "uid")

---

plugins/ldap-change-password/ChangePasswordLdapDriver.php
plugins/ldap-change-password/index.php

* added ldap start_tls support
* added gecos token for use in LDAP user DN in case your user accounts are using cn as rdn.

start tls and gecos

---

plugins/contact-group-excel-paste/js/excel_contact_group.js

Fixes a regression of plugin contact-group-excel-paste since an update of rainloop that modified CSS classes and JavaScript of autocomplete fields

Fix regression

---

rainloop/v/0.0.0/app/libraries/MailSo/Mail/MailClient.php

This PR changes the sorting of IMAP messages to use the message date (DATE) instead of the arrival date (ARRIVAL) in order to sort the messages in the mailbox pane view correctly.
This fixes issue #1817.

Use DATE instead of ARRIVAL for sorting messages (Fixes #1817)

---

rainloop/v/0.0.0/app/libraries/RainLoop/Config/Application.php

This uses the built-in `password_hash` and `password_verify` when available to replace the insecure md5 hash of the admin password. Falls back to the current algorithm. Also continues to recognize and support existing md5 hashes, changing the admin password will re-hash with the new algorithm.
Note that `password_hash` is using bcrypt by default in the current version of PHP, the default algorithm may change over time. `password_verify` will recognize different standard hash algorithms and verify them all as needed allowing forward compatibility.
Fixes #1816 and #1635 
(will submit another PR to address the weak salt generation)

Switch admin password hashing to secure algorithms when available

---

rainloop/v/0.0.0/app/localization/webmail/fi_FI.yml

"Empty list" description in empty folders is translated to a verb (empty, tyhjennä) instead of a adjective (empty, tyhjä).
https://fi.glosbe.com/fi/en/tyhjent%C3%A4%C3%A4 (empty, verb)
https://fi.glosbe.com/fi/en/tyhj%C3%A4 (empty, adjective)

Mispelling in fi_FI translation

---

dev/Model/Message.js

People are sending me emails with a lot of images. Right now only images that are lazy loaded before (in the normal message view) are shown in print view or view in separate window. With this patch all images are loaded.

Load image data for all images

---

rainloop/v/0.0.0/app/libraries/RainLoop/Service.php

Currently when the admin page is disabled you'll get an 200 OK with a message, that access is denied. This PR instead throws a 403 Forbidden to be more in line with the content of the page.
fixes #1838

throw 403 on access denied

---

rainloop/v/0.0.0/app/libraries/RainLoop/Common/PdoAbstract.php

The table `rainloop_system` is the only table without a primary key which isn't good. For databases with `pxc_strict_mode = ENFORCING or MASTER` this proves impossible to use as a Storage (PDO) and it isn't a good practice.
This PR adds a primary key to `rainloop_system` table.
Here is the error that is thrown:

Add missing primary key to rainloop_system table

---

plugins/postfixadmin-change-password/ChangePasswordPostfixAdminDriver.php
plugins/postfixadmin-change-password/index.php

My mail server was set up with `dovecot:ARGON2I` password encryption option.  This allows people who set up argon2i as the encryption method to continue using it when users change their password with the plugin.

plugins/postfixadmin-change-password: Add "ARGON2I"
